### ISSUE TITLE
看到第二个答案MVC时候的疑问

### ISSUE THREAD

**Issue by JackStronger** [liberalisman/Interview-QA#1]
之前看斯坦福大学关于MVC模式的那个视频讲到MVC中的M和V之间是不允许通信的，而是通过C作为桥梁。所以，这里为什么说MVC模式所有的模块通信都是单向的？

**Comment by liberalisman** [comment]
其实我也认为 MVC是依靠C进行过渡M和V之间不该有通信。我画的图是借用阮一峰的说法。此处可以存疑。

**Comment by JackStronger** [comment]
他那篇更针对于Javascript的吧。

**Comment by liberalisman** [comment]
巧了，我正在找斯坦福白胡子大叔的视频呢，我正好看一遍学习一下
