### ISSUE TITLE
第5题解释的有些问题

### ISSUE THREAD

**Issue by hrscy** [liberalisman/Interview-QA#3]
[5.NSString为什么要用copy关键字，如果用strong会有什么问题？](https://github.com/liberalisman/iOS-Interview-Question-Answer#5nsstring为什么要用copy关键字如果用strong会有什么问题)
该题回答的不够全面。
NSString 使用 copy 和它的子类并没有关系，而且凡是 NSObject 都有 copy 方法，并不是 NSString 独有。
既然你提到了 NSMutableString，那么就应该会想到还有一个和 copy 对应的 mutableCopy 方法。
如下代码：
```
NSString *string = @"测试数据";
NSString *copyString = [string copy]；
NSMutableString *mutableCopyString = [string mutableCopy];
NSMutableString *copyMutableString = [string copy];
NSLog(@"%p,%p,%p,%p", string, copyString, mutableCopyString, copyMutableString);
```
输出它们的地址，string 和 copyString 的地址是相同的，说明它们的指针指向同一个地址，也就是说 copy 是浅拷贝，即指针拷贝；mutableCopyString 和其他的地址都不一样，说明新开辟了一块内存空间，也就是和前两个没有任何关系，也就是说 mutableCopy 发生了深拷贝；copyMutableString 和其他的地址也不一样，同 mutableCopyString ，也是发生了深拷贝。
对于 copyString 和 copyMutableString 同是使用的 copy，但是地址却不一样，是因为苹果对于不可变的对象执行的引用操作，而对于可变对象，相对于之前的不可变对象，那么地址肯定会不一样，所以这个时候就要拷贝一份，和之前的就没有任何关系了。
还有就是属性中的 copy 关键字，如下代码：
```
@property (nonatomic, copy) NSString *copyString;
@property (nonatomic, strong) NSString *strongString;
```
对于上面的代码，copyString 和 strongString 的 set 方法中，
```
-(void)setCopyString:(NSString *)copyString {
    _copyString = [copyString copy];  // 调用 copy 方法，所以并不是直接赋值
}
-(void)setStrongString:(NSString *)strongString {
    _strongString = strongString;  // 直接引用
}
```
如果想要外界赋值的值对 string 有影响，那么就用 strong，这样两者相当于还是一个对象，如果在赋值以后不想要外界再对string 有影响，那么就用 copy。也就是说用 strong 还是 copy 可以根据情况而定。

**Comment by liberalisman** [comment]
很感谢您的补充，您说的很全面，之前的解释确实不够完整，我在写之初考虑过这个问题，但感觉话题如果展开，篇幅会过长，所以精简回答。我会将您的补充添加到原文中，非常感谢
