### ISSUE TITLE
第 19题 参考答案

### ISSUE THREAD

**Issue by ziyouzhe4** [liberalisman/Interview-QA#4]
遵循三个规则(约束条件)
1. 子类如果有指定初始化函数，那么指定初始化函数实现时必须调用它的直接父类的指定初始化函数。
2. 如果子类有指定初始化函数，那么便利初始化函数必须调用自己的其它初始化函数(包括指定初始化函数以及其他的便利初始化函数)，不能调用super的初始化函数。
3. 如果子类提供了指定初始化函数，那么一定要实现所有父类的指定初始化函数。

**Comment by liberalisman** [comment]
感谢补充
